name: Docker Image CI
on:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-docker-image .
        working-directory: ./Dockerfile
      
      - name: Run Bash Script
        run: chmod +x display_name.sh 
      - name: Run Bash Script
        run: ./display_name.sh


            
 
